routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



	 
Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

	

	

    /*Todas las rutas que esten en este grupo estaran restringidas si nuestro aplicacion esta
	en mantenimiento y se restringira su paso si la pagina esta en mantenimiento.*/
	Route::get('/home', 'HomeController@index')->name('home');

	//Route::get('/', 'HomeController@index');
 	//////////// chat de usuarios //////////////
	Route::get('/load-latest-messages', 'MessagesController@getLoadLatestMessages');
 
	Route::post('/send', 'MessagesController@postSendMessage');
	 
	Route::get('/fetch-old-messages', 'MessagesController@getOldMessages');
	
	/////////////////////////////////articulos/////////////////////////
	Route::resource('articulos','ArticuloController');
	Route::post('/articulos/create', 'ArticuloController@store');
	Route::put('/{id}', 'ArticuloController@update');

	/////////////////////////////////tiendas/////////////////////////
	Route::resource('tiendas','TiendaController');
	Route::post('/tiendas/create', 'TiendaController@store');
	Route::put('/{id}', 'TiendaController@update');

	/////////////////////////////////vendedores/////////////////////////
	Route::resource('personal','VendedorController');
	Route::post('/personal/create', 'VendedorController@store');
	Route::put('/{id}', 'VendedorController@update');


	/////////////////////////////////clientes/////////////////////////
	Route::resource('clientes','ClienteController');
	Route::post('/clientes/create', 'ClienteController@store');
	Route::put('/{id}', 'ClienteController@update');

	/////////////////////////////////ventas/////////////////////////

	Route::resource('ventas','VentaController');

	Route::post('/ventas/create', 'VentaController@store');
	Route::post('/ventas/ticket_compra', 'VentaController@create');
	Route::post('/ventas/articulo', 'VentaController@articulo_stock');

	Route::put('/{id}', 'VentaController@update');
	//Route::post('/ventas/enviarcheck', 'VentaController@enviarcheck');
	Route::get('ventas/{id}/traerArticulo', 'VentaController@enviarcheck');

	/////////////////////////////////venta registradas/////////////////////////
	Route::resource('ventas_registradas','VentaregistroController');
	Route::post('/ventas_registradas/create', 'VentaregistroController@store');
	Route::put('/{id}', 'VentaregistroController@update');

	/////////////////////////////////categorias/////////////////////////
	Route::resource('categorias','CategoriaController');
	Route::post('/categorias/create', 'CategoriaController@store');
	Route::put('/{id}', 'CategoriaController@update');

	/////////////////////////////////tipo_usuarios/////////////////////////
	Route::resource('tipo_usuarios','TipoUsuarioController');
	Route::post('/tipo_usuarios/create', 'TipoUsuarioController@store');
	Route::put('/{id}', 'TipoUsuarioController@update');

	/////////////////////////////////usuarios/////////////////////////
	Route::resource('usuarios','UsuarioController');
	Route::post('/permisos', 'UsuarioController@permisos');
	Route::post('/borrar_permisos', 'UsuarioController@borrar_permisos');
	Route::post('/usuarios/create', 'UsuarioController@store');
	Route::put('/{id}', 'UsuarioController@update');
	

	/////////////////////////////////perfiles/////////////////////////
	Route::resource('perfiles','PerfilController');

	/////////////////////////////////chat/////////////////////////
	Route::resource('chats','ChatController');

	/////////////////////////////////descuentos/////////////////////////
	Route::resource('descuentos','DescuentoController');
	Route::post('/descuentos/create', 'DescuentoController@store');
	Route::put('/{id}', 'DescuentoController@update');

	/////////////////////////////////promociones/////////////////////////
	Route::resource('promociones','PromocionController');
	Route::post('/promociones/create', 'PromocionController@store');
	Route::put('/{id}', 'PromocionController@update');

	/////////////////////////////////configuraciones/////////////////////////
	Route::resource('configuraciones','ConfiguracionController');
	Route::post('/configuraciones/create', 'ConfiguracionController@store');
	Route::put('/{id}', 'ConfiguracionController@update');


	/////////////////////////////////configuraciones/////////////////////////
	Route::resource('incidencias','IncidenciaController');
	Route::post('/incidencias/create', 'IncidenciaController@store');
	Route::put('/{id}', 'IncidenciaController@update');

	///////////////////////// Cierrre de Sesión ///////////////
	Route::get('logout', function (){
		Auth::logout();
		return redirect('/');
	});







	




	


	

resources/views/configuraciones/create.blade.php
@extends('layouts.inicio')

@section('content')
<div class="col-md-12">
	<div class="box box-primary">
	    <div class="box-header with-border">
	    	@isset($configuraciones)
	    	<h3 class="box-title">Actualizar configuracion</h3>
			@else
			<h3 class="box-title">Nuevo configuracion</h3>
			@endisset
	    </div>
	    <!-- /.box-header -->
	    <!-- form start -->
	    @isset($configuraciones)
	        <form action="{{ route('configuraciones.update',$configuraciones->id) }}" method="POST" enctype="multipart/form-data">
	        @csrf
	        @method('PUT')
	      @else
	        <form action="{{ route('configuraciones.store') }}" method="POST" enctype="multipart/form-data">
	        @csrf
	      @endisset
	      <div class="box-body">
	      	<div class="col-md-4">
	      	<div class="form-group">
	          <label for="exampleInputPassword1">Nombre de la Empresa</label>
	          <input type="text" class="form-control" name="nombre_empresa" placeholder="Nombre de la Empresa" value="@isset($configuraciones){{ $configuraciones->nombre_empresa }}@endisset">
	        </div>
	    	</div>
	    	<div class="col-md-4">
		        <div class="form-group">
		          <label for="exampleInputEmail1">Nombre Corto</label>
		          <input type="text" class="form-control" name="nombre_corto" placeholder="Nombre Corto" value="@isset($configuraciones){{ $configuraciones->nombre_corto }}@endisset">
		        </div>
	    	</div>
	    	<div class="col-md-4">
		        <div class="form-group">
		          <label for="exampleInputPassword1">Dirección</label>
		          <input type="text" class="form-control" name="direccion" placeholder="Dirección" value="@isset($configuraciones){{ $configuraciones->direccion }}@endisset">
		        </div>
		    </div>
		    <div class="col-md-4">
		        <div class="form-group">
		          <label for="exampleInputPassword1">Codigo Postal</label>
		          <input type="text" class="form-control" name="cp" placeholder="Codigo Postal" value="@isset($configuraciones){{ $configuraciones->cp }}@endisset">
		        </div>
	        </div>
	        <div class="col-md-4">
		        <div class="form-group">
		          <label for="exampleInputPassword1">Correo Electronico</label>
		          <input type="email" class="form-control" name="correo_electronico" placeholder="Correo Electronico" value="@isset($configuraciones){{ $configuraciones->correo_electronico }}@endisset">
		        </div>
		    </div>

		    <div class="col-md-4">
		        <div class="form-group">
		          <label for="exampleInputPassword1">Telefono</label>
		          <input type="text" class="form-control" name="telefono" placeholder="Telefono" value="@isset($configuraciones){{ $configuraciones->telefono }}@endisset">
		        </div>
		    </div>


		    <div class="col-md-4">
              	<div class="form-group">
	                <label>Color Skin</label>
	                <select class="form-control select2 select2-hidden-accessible" style="width: 100%;"  name="cambiar_skin" tabindex="-1" aria-hidden="true">
	                 @isset($configuraciones)
	                 <option value="{{ $configuraciones->cambiar_skin }}">
	                 	<?php 
	                 		if ($configuraciones->cambiar_skin == 'skin-blue') {
	                 			echo 'Color Azul';
	                 		}elseif($configuraciones->cambiar_skin == 'skin-green'){
	                 			echo 'Color Verde';
	                 		}elseif($configuraciones->cambiar_skin == 'skin-purple'){
	                 			echo 'Color Morado';	
	                 		}elseif($configuraciones->cambiar_skin == 'skin-red'){
	                 			echo 'Color Rojo';
	                 		}elseif($configuraciones->cambiar_skin == 'skin-yellow'){
	                 			echo 'Color Amarillo';
	                 		}
	                 	 ?>
	                 </option>
	                 @else
	                 <option>Selecciona un Color</option>
	                 @endisset
	                  <option value="skin-blue">Color Azul</option>
	                  <option value="skin-green">Color Verde</option>
	                  <option value="skin-purple">Color Morado</option>
	                  <option value="skin-red">Color Rojo</option>
	                  <option value="skin-yellow">Color Amarillo</option>

	                </select>
            	</div>
              
            </div>

		    @isset($configuraciones)
            <div class="col-md-4">
              	<div class="form-group">
	                <label>Logo Empresa</label>
	                <div style="height: 20px;"></div>
	                <img src="../../images/{{ $configuraciones->logo_empresa }}" alt="" width="120" height="120">
	                <br>
	                <label>Cambiar Imagen</label>
                    <input type="file"  name="avatar" value="">
	            </div>
	        </div>

            
            @else
            <div class="col-md-4">
		        <div class="form-group">
		          <label for="exampleInputPassword1">Logo Empresa</label>
		          <input type="file"  name="avatar" value="">
		        </div>
		    </div>
		    @endisset


	        
	      </div>
	      <!-- /.box-body -->

	      <div class="box-footer">
	      	<a href="{{ url('configuraciones') }}" class="btn btn-warning"> <i class="fa fa-arrow-left"></i> Regresar</a>
	      	@isset($configuraciones)
	      	<button type="submit" class="btn btn-primary btn-submit"><i class="fa fa-repeat"></i> Actualizar</button>
	      	@else
	        <button type="submit" class="btn btn-primary btn-submit"><i class="fa fa-save"></i> Agregar</button>
	        @endisset
	      </div>
	    </form>
	  </div>
</div>

<!--<script>
	$(document).ready( function () {


	    $(".btn-submit").click(function(e){

	    
        e.preventDefault();

        var nombre_empresa = $("input[name=nombre_empresa]").val();
        var nombre_corto = $("input[name=nombre_corto]").val();
        var direccion = $("input[name=direccion]").val();
        var cp = $("input[name=cp]").val();
        var correo_electronico = $("input[name=correo_electronico]").val();
        var telefono = $("input[name=telefono]").val();
        var logo_empresa = $("input[name=logo_empresa]").val();
        var imagen_login = $("input[name=imagen_login]").val();





        if(nombre_empresa == '' || correo_electronico == ''){

        	
        	swal("Upss!", "Lo sentimos Campos Vacios", "warning");
        	

        }else{

        	$.ajax({

	           type:"{{ ( isset($configuraciones) ? 'PUT' : 'POST' ) }}",

	           url:"{{ ( isset($configuraciones) ) ? '/configuraciones/' . $configuraciones->id : '/configuraciones/create' }}",
	           headers: {
				      'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
				     },
	           data:{
	           	nombre_empresa:nombre_empresa,
				nombre_corto:nombre_corto,
				direccion:direccion,
				cp:cp,
				correo_electronico:correo_electronico,
				telefono:telefono,
				logo_empresa:logo_empresa,
				imagen_login:imagen_login,
				
	           },
	           
	            success:function(data){
	                swal({title: "Felicidades!", text: data.success, type: "success"}, function(){ location.href ="{{ url('configuraciones') }}"; } );
	            }


	        });

        }

  });
}); 
</script>-->
@endsection

resources/views/configuraciones/index.blade.php
@extends('layouts.inicio')

@section('content')
<div class="col-md-12">
  <!-- MAP & BOX PANE -->
  <div class="box box-primary">
    <div class="box-header with-border">
      <h3 class="box-title"><img class="img-circle" src="../images/<?php list($confi) = configuracion(); print_r($confi->logo_empresa);?>" alt="User Avatar" heigth="30" width="30"> Configuración <?php list($confi) = configuracion(); print_r($confi->nombre_empresa);?> </h3>

      <div class="box-tools pull-right">
        <a href="{{ route('configuraciones.create') }}" class="btn btn-primary"><i class="fa fa-plus"></i> Nueva Configuración</a>
      </div>
    </div>
    <!-- /.box-header -->
    <div class="box-body no-padding">

    	  <table id="example" class="display" style="width:100%">
	        <thead>
	          <tr align="center">
              <th>Nombre </th>
	            <th>Nombre Corto</th>
	            <!--<th>Direccioón</th>-->
	            <!--<th>Codigo Postal</th>-->
              <th>Correo Electronico</th>
              <th>Telefono</th>
              <th>logo Empresa</th>
              <th>Color de Tema</th>
	            <th>Acciones</th>
	          </tr>
	        </thead>
	        <tbody>
	          @foreach ($configuraciones_table as $configuracion)
                  <tr align="center">
                      <td>{{ $configuracion->nombre_empresa }}</td>
                      <td>{{ $configuracion->nombre_corto }}</td>
                      <!--<td>{{ $configuracion->direccion }}</td>-->
                      <!--<td>{{ $configuracion->cp }}</td>-->
                      <td>{{ $configuracion->correo_electronico }}</td>
                      <td>{{ $configuracion->telefono }}</td>
                      <td><img src="../../images/<?php echo $configuracion->logo_empresa; ?>" heigth="50" width="50"></td>
                      <td>
                        <?php 
                           if ($configuracion->cambiar_skin == 'skin-blue') {
                              echo 'Color Azul';
                            }elseif($configuracion->cambiar_skin == 'skin-green'){
                              echo 'Color Verde';
                            }elseif($configuracion->cambiar_skin == 'skin-purple'){
                              echo 'Color Morado';  
                            }elseif($configuracion->cambiar_skin == 'skin-red'){
                              echo 'Color Rojo';
                            }elseif($configuracion->cambiar_skin == 'skin-yellow'){
                              echo 'Color Amarillo';
                            }
                        ?>
                      </td>

                      <td >
                        <form action="{{ route('configuraciones.destroy',$configuracion->id )}}" method="POST">
                                      @csrf
                                      @method('DELETE')
                        <div class="btn-group">
                          <button type="button" class="btn btn-warning "><a href="{{ route('configuraciones.edit',$configuracion->id)}}" style="color:#fff;"><i class="fa fa-pencil"></i> Editar</a></button>
                            <button class="btn btn-danger" type="submit"><i class="fa fa-trash"></i> Eliminar</button>
                        </div>
                        </form>
                        
                      </td>
                  </tr>
                @endforeach
	        </tbody>
	      </table>
    </div>
    <!-- /.box-body -->
  </div>
  <!-- /.box -->

</div>
<script>
  $(document).ready(function() {
      
      $('#example').DataTable({
    
    "scrollY": 300,
    "scrollX": true,
    "pagingType": "full_numbers",
   language: {
    processing:     "Tratamiento en curso...",
    search:         "Buscar&nbsp;:",
    lengthMenu:    "Mostrando _MENU_ registros por página",
    info:           "Mostrando página _START_ a _TOTAL_ Elementos",
    infoEmpty:      "No hay registros disponibles",
    infoFiltered:   "(Filtrado de _MAX_ registros totales)",
    infoPostFix:    "",
    loadingRecords: "Cargando...",
    zeroRecords:    "Ningun Resgistro",
    emptyTable:     "No hay datos disponibles por el momento.",
    paginate: {
        first:      "Primeramente",
        previous:   "Anteriormente",
        next:       "Siguiente",
        last:       "Ultimo"
    },
    aria: {
        sortAscending:  ": Activar para ordenar la columna en orden ascendente.",
        sortDescending: ": Activar para ordenar la columna en orden descendente."
    }
},
dom: 'B<"clear">lfrtip',
    buttons: [
        'colvis'
    ],
});
      
  } );
</script>
@endsection