routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



	 
Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

	

	

    /*Todas las rutas que esten en este grupo estaran restringidas si nuestro aplicacion esta
	en mantenimiento y se restringira su paso si la pagina esta en mantenimiento.*/
	Route::get('/home', 'HomeController@index')->name('home');

	//Route::get('/', 'HomeController@index');
 	//////////// chat de usuarios //////////////
	Route::get('/load-latest-messages', 'MessagesController@getLoadLatestMessages');
 
	Route::post('/send', 'MessagesController@postSendMessage');
	 
	Route::get('/fetch-old-messages', 'MessagesController@getOldMessages');
	
	/////////////////////////////////articulos/////////////////////////
	Route::resource('articulos','ArticuloController');
	Route::post('/articulos/create', 'ArticuloController@store');
	Route::put('/{id}', 'ArticuloController@update');

	/////////////////////////////////tiendas/////////////////////////
	Route::resource('tiendas','TiendaController');
	Route::post('/tiendas/create', 'TiendaController@store');
	Route::put('/{id}', 'TiendaController@update');

	/////////////////////////////////vendedores/////////////////////////
	Route::resource('personal','VendedorController');
	Route::post('/personal/create', 'VendedorController@store');
	Route::put('/{id}', 'VendedorController@update');


	/////////////////////////////////clientes/////////////////////////
	Route::resource('clientes','ClienteController');
	Route::post('/clientes/create', 'ClienteController@store');
	Route::put('/{id}', 'ClienteController@update');

	/////////////////////////////////ventas/////////////////////////

	Route::resource('ventas','VentaController');

	Route::post('/ventas/create', 'VentaController@store');
	Route::post('/ventas/ticket_compra', 'VentaController@create');
	Route::post('/ventas/articulo', 'VentaController@articulo_stock');

	Route::put('/{id}', 'VentaController@update');
	//Route::post('/ventas/enviarcheck', 'VentaController@enviarcheck');
	Route::get('ventas/{id}/traerArticulo', 'VentaController@enviarcheck');

	/////////////////////////////////venta registradas/////////////////////////
	Route::resource('ventas_registradas','VentaregistroController');
	Route::post('/ventas_registradas/create', 'VentaregistroController@store');
	Route::put('/{id}', 'VentaregistroController@update');

	/////////////////////////////////categorias/////////////////////////
	Route::resource('categorias','CategoriaController');
	Route::post('/categorias/create', 'CategoriaController@store');
	Route::put('/{id}', 'CategoriaController@update');

	/////////////////////////////////tipo_usuarios/////////////////////////
	Route::resource('tipo_usuarios','TipoUsuarioController');
	Route::post('/tipo_usuarios/create', 'TipoUsuarioController@store');
	Route::put('/{id}', 'TipoUsuarioController@update');

	/////////////////////////////////usuarios/////////////////////////
	Route::resource('usuarios','UsuarioController');
	Route::post('/permisos', 'UsuarioController@permisos');
	Route::post('/borrar_permisos', 'UsuarioController@borrar_permisos');
	Route::post('/usuarios/create', 'UsuarioController@store');
	Route::put('/{id}', 'UsuarioController@update');
	

	/////////////////////////////////perfiles/////////////////////////
	Route::resource('perfiles','PerfilController');

	/////////////////////////////////chat/////////////////////////
	Route::resource('chats','ChatController');

	/////////////////////////////////descuentos/////////////////////////
	Route::resource('descuentos','DescuentoController');
	Route::post('/descuentos/create', 'DescuentoController@store');
	Route::put('/{id}', 'DescuentoController@update');

	/////////////////////////////////promociones/////////////////////////
	Route::resource('promociones','PromocionController');
	Route::post('/promociones/create', 'PromocionController@store');
	Route::put('/{id}', 'PromocionController@update');

	/////////////////////////////////configuraciones/////////////////////////
	Route::resource('configuraciones','ConfiguracionController');
	Route::post('/configuraciones/create', 'ConfiguracionController@store');
	Route::put('/{id}', 'ConfiguracionController@update');


	/////////////////////////////////configuraciones/////////////////////////
	Route::resource('incidencias','IncidenciaController');
	Route::post('/incidencias/create', 'IncidenciaController@store');
	Route::put('/{id}', 'IncidenciaController@update');

	///////////////////////// Cierrre de Sesión ///////////////
	Route::get('logout', function (){
		Auth::logout();
		return redirect('/');
	});







	




	


	

app/Incidencia.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Incidencia extends Model
{
	protected $hidden = ['created_at','updated_at'];
    protected $fillable = ['id','titulo_incidencia','tipo_incidencia','tipo_incidencia','observacion','imagen','activo'];
    protected $table = 'incidencias_sistema';

    
}

app/Http/Controllers/IncidenciaController.php
<?php

namespace App\Http\Controllers;
use Illuminate\Http\Request;

use App\Incidencia;
use Auth;



class IncidenciaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
       

       $datos['incidencias'] = Incidencia::where([['activo','1']])->get();

        return view('incidencias.index')->with($datos);

        //return view('perfiles.index');
    }



    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        
      return view('incidencias.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
     public function show($id)
    {
        
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
   
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request,$id)
    {

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {

    }






}

resources/views/incidencias/create.blade.php
@extends('layouts.inicio')

@section('content')

<div class="col-md-12">
	<div class="box box-primary">
	    <div class="box-header with-border">
	    	@isset($usuarios)
	    	<h3 class="box-title">Actualizar Usuario</h3>
			@else
			<h3 class="box-title">Nuevo Usuario</h3>
			@endisset
	    </div>
	    <!-- /.box-header -->
	    <!-- form start -->

	    @isset($usuarios)
	        <form action="{{ route('usuarios.update',$usuarios->id) }}" method="POST" enctype="multipart/form-data">
	        @csrf
	        @method('PUT')
	      @else
	        <form action="{{ route('usuarios.store') }}" method="POST" enctype="multipart/form-data">
	        @csrf
	      @endisset
	      <div class="box-body">
	      	<div class="col-md-6">
	      	<div class="form-group">
	          <label for="exampleInputPassword1">Nombre del Usuario</label>
	          <input type="text" class="form-control" name="name" placeholder="Nombre de Articulo" value="@isset($usuarios){{ $usuarios->name }}@endisset">
	        </div>
	    	</div>
	    	<div class="col-md-6">
		        <div class="form-group">
		          <label for="exampleInputEmail1">Correo Electronico</label>
		          <input type="text" class="form-control" name="email" placeholder="Correo Electronico" value="@isset($usuarios){{ $usuarios->email }}@endisset">
		        </div>
	    	</div>
	    	<div class="col-md-6">
		        <div class="form-group">
		          <label for="exampleInputPassword1">Password</label>
		          <input type="text" class="form-control" name="password" placeholder="Password" value="@isset($usuarios){{ $usuarios->password_name }}@endisset">
		        </div>
		    </div>

		    

	        <div class="col-md-6">
              	<div class="form-group">
	                <label>Tipo de Usuario</label>
	                <select class="form-control select2 select2-hidden-accessible" style="width: 100%;"  name="tipo_user" tabindex="-1" aria-hidden="true">
	                 @isset($usuarios)
	                	 <option value="{{ $usuarios->tipo_user }}">{{ $usuarios->_TipoUsuario->nombre }}</option>
	                 @else
	                 <option>Selecciona una Categoria</option>
	                 @endisset
	                  
	                </select>
            	</div>
              
            </div>
            
            <div class="col-md-12">

            	<div class="col-md-6 ">
	              	<div class="form-group">
		                <label>Permisos</label>
		                <select class="form-control select2 select2-hidden-accessible" style="width: 100%;" id="id_permiso" name="id_permiso" tabindex="-1" aria-hidden="true">
		                 <option value="0">Selecciona un Permiso</option>
		                  
		                </select>
	            	</div>
	              	<br>
	              	<button type="button" class="btn btn-primary pull-right" id="agregarArticulo"><i class="fa fa-check"></i> Agregar</button>



				      
			        	<button type="button" class="btn btn-primary btn-submit pull-right"><i class="fa fa-check"></i> Agregar Permisos</button>

            	</div>


            	<div class="col-md-6">

	        		 @isset($usuarios)
		            <div class="col-md-6">
		              	<div class="form-group">
			                <label>Imagen de Usuario</label>
			                <div style="height: 20px;"></div>
			                <img src="../../images/{{ $usuarios->imagen_usuario }}" alt="" width="120" height="120">
			                <br>
			                <label>Cambiar Imagen</label>
		                    <input type="file"  name="avatar" value="">
			            </div>
			        </div>


		            
		            @else
		            <div class="col-md-6">
				        <div class="form-group">
				          <label for="exampleInputPassword1">Imagen del Usuario</label>
				          <input type="file"  name="avatar" value="">
				        </div>
				    </div>
				    @endisset
            	</div>

            </div>

		      

		      <!-- /.row -->
		    


           
            
            
            
		    
            @isset($usuarios)
            <input type="hidden" name="id_personal" value="@isset($usuarios){{ $usuarios->id_personal }}@endisset">
            <input type="hidden" name="tipo_user_2" value="@isset($usuarios){{ $usuarios->tipo_user }}@endisset">
            <input type="hidden" name="id" value="@isset($usuarios){{ $usuarios->id }}@endisset">
	        @endisset
	      </div>
	      <!-- /.box-body -->

	      <div class="box-footer">
	      	<a href="{{ url('usuarios') }}" ><button type="button" class="btn btn-warning"><i class="fa fa-arrow-left"></i> Regresar</button></a>
	      	@isset($usuarios)
	      	<button type="submit" class="btn btn-primary "><i class="fa fa-repeat"></i> Actualizar</button>
	      	@else
	        <button type="submit" class="btn btn-primary "><i class="fa fa-save"></i> Agregar</button>
	        @endisset
	      </div>
	    </form>
	  </div>
</div>
@endsection

resources/views/incidencias/index.blade.php
@extends('layouts.inicio')

@section('content')
<div class="col-md-12">
  <!-- MAP & BOX PANE -->
  <div class="box box-primary">
    <div class="box-header with-border">
     
      <h3 class="box-title"><img class="img-circle" src="../images/<?php list($confi) = configuracion(); print_r($confi->logo_empresa);?>" alt="User Avatar" heigth="30" width="30"> Incidencias de Sistema <?php list($confi) = configuracion(); print_r($confi->nombre_empresa);?> </h3>


      <div class="box-tools pull-right">
        <a href="{{ route('incidencias.create') }}" class="btn btn-primary"><i class="fa fa-plus"></i> Nueva Incidencia</a>
      </div>
    </div>
    <!-- /.box-header -->
    <div class="box-body no-padding">

    	  <table id="example" class="display" style="width:100%">
	        <thead>
	          <tr align="center">
              <th>Nombre incidencia</th>
              <th>Fecha Incidencia</th>
              <th>Tipo de incidencia</th>
	            <th>Acciones</th>
	          </tr>
	        </thead>
	        <tbody>
	          @foreach ($incidencias as $incidencia)
                  <tr align="center">
                      <td>{{ $incidencia->titulo_incidencia }}</td>
                      <td>{{ $incidencia->created_at }}</td>
                      <td>{{ $incidencia->tipo_incidencia }}</td>
                      <td >
                        <form action="{{ route('incidencias.destroy',$incidencia->id )}}" method="POST">
                                      @csrf
                                      @method('DELETE')
                        <div class="btn-group">
                          <button type="button" class="btn btn-warning"><a href="{{ route('incidencias.edit',$incidencia->id)}}" style="color:#fff;"><i class="fa fa-pencil"></i> Editar</a></button>
                          <button class="btn btn-danger" type="submit"><i class="fa fa-trash"></i> Eliminar</button>
                        </div>
                        </form>
                      </td>
                  </tr>
                @endforeach
	        </tbody>
	      </table>
    </div>
    <!-- /.box-body -->
  </div>
  <!-- /.box -->

</div>
<script>
  $(document).ready(function() {
      
      $('#example').DataTable({
    
    "scrollY": 300,
    "scrollX": true,
    "pagingType": "full_numbers",
   language: {
    processing:     "Tratamiento en curso...",
    search:         "Buscar&nbsp;:",
    lengthMenu:    "Mostrando _MENU_ registros por página",
    info:           "Mostrando página _START_ a _TOTAL_ Elementos",
    infoEmpty:      "No hay registros disponibles",
    infoFiltered:   "(Filtrado de _MAX_ registros totales)",
    infoPostFix:    "",
    loadingRecords: "Cargando...",
    zeroRecords:    "Ningun Resgistro",
    emptyTable:     "No hay datos disponibles por el momento.",
    paginate: {
        first:      "Primeramente",
        previous:   "Anteriormente",
        next:       "Siguiente",
        last:       "Ultimo"
    },
    aria: {
        sortAscending:  ": Activar para ordenar la columna en orden ascendente.",
        sortDescending: ": Activar para ordenar la columna en orden descendente."
    }
},
dom: 'B<"clear">lfrtip',
    buttons: [
        'colvis'
    ],
});
      
  } );
</script>
@endsection