routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



	 
Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

	

	

    /*Todas las rutas que esten en este grupo estaran restringidas si nuestro aplicacion esta
	en mantenimiento y se restringira su paso si la pagina esta en mantenimiento.*/
	Route::get('/home', 'HomeController@index')->name('home');

	//Route::get('/', 'HomeController@index');
 	//////////// chat de usuarios //////////////
	Route::get('/load-latest-messages', 'MessagesController@getLoadLatestMessages');
 
	Route::post('/send', 'MessagesController@postSendMessage');
	 
	Route::get('/fetch-old-messages', 'MessagesController@getOldMessages');
	
	/////////////////////////////////articulos/////////////////////////
	Route::resource('articulos','ArticuloController');
	Route::post('/articulos/create', 'ArticuloController@store');
	Route::put('/{id}', 'ArticuloController@update');

	/////////////////////////////////tiendas/////////////////////////
	Route::resource('tiendas','TiendaController');
	Route::post('/tiendas/create', 'TiendaController@store');
	Route::put('/{id}', 'TiendaController@update');

	/////////////////////////////////vendedores/////////////////////////
	Route::resource('personal','VendedorController');
	Route::post('/personal/create', 'VendedorController@store');
	Route::put('/{id}', 'VendedorController@update');


	/////////////////////////////////clientes/////////////////////////
	Route::resource('clientes','ClienteController');
	Route::post('/clientes/create', 'ClienteController@store');
	Route::put('/{id}', 'ClienteController@update');

	/////////////////////////////////ventas/////////////////////////

	Route::resource('ventas','VentaController');

	Route::post('/ventas/create', 'VentaController@store');
	Route::post('/ventas/ticket_compra', 'VentaController@create');
	Route::post('/ventas/articulo', 'VentaController@articulo_stock');

	Route::put('/{id}', 'VentaController@update');
	//Route::post('/ventas/enviarcheck', 'VentaController@enviarcheck');
	Route::get('ventas/{id}/traerArticulo', 'VentaController@enviarcheck');

	/////////////////////////////////venta registradas/////////////////////////
	Route::resource('ventas_registradas','VentaregistroController');
	Route::post('/ventas_registradas/create', 'VentaregistroController@store');
	Route::put('/{id}', 'VentaregistroController@update');

	/////////////////////////////////categorias/////////////////////////
	Route::resource('categorias','CategoriaController');
	Route::post('/categorias/create', 'CategoriaController@store');
	Route::put('/{id}', 'CategoriaController@update');

	/////////////////////////////////tipo_usuarios/////////////////////////
	Route::resource('tipo_usuarios','TipoUsuarioController');
	Route::post('/tipo_usuarios/create', 'TipoUsuarioController@store');
	Route::put('/{id}', 'TipoUsuarioController@update');

	/////////////////////////////////usuarios/////////////////////////
	Route::resource('usuarios','UsuarioController');
	Route::post('/permisos', 'UsuarioController@permisos');
	Route::post('/borrar_permisos', 'UsuarioController@borrar_permisos');
	Route::post('/usuarios/create', 'UsuarioController@store');
	Route::put('/{id}', 'UsuarioController@update');
	

	/////////////////////////////////perfiles/////////////////////////
	Route::resource('perfiles','PerfilController');

	/////////////////////////////////chat/////////////////////////
	Route::resource('chats','ChatController');

	/////////////////////////////////descuentos/////////////////////////
	Route::resource('descuentos','DescuentoController');
	Route::post('/descuentos/create', 'DescuentoController@store');
	Route::put('/{id}', 'DescuentoController@update');

	/////////////////////////////////promociones/////////////////////////
	Route::resource('promociones','PromocionController');
	Route::post('/promociones/create', 'PromocionController@store');
	Route::put('/{id}', 'PromocionController@update');

	/////////////////////////////////configuraciones/////////////////////////
	Route::resource('configuraciones','ConfiguracionController');
	Route::post('/configuraciones/create', 'ConfiguracionController@store');
	Route::put('/{id}', 'ConfiguracionController@update');


	/////////////////////////////////configuraciones/////////////////////////
	Route::resource('incidencias','IncidenciaController');
	Route::post('/incidencias/create', 'IncidenciaController@store');
	Route::put('/{id}', 'IncidenciaController@update');

	///////////////////////// Cierrre de Sesión ///////////////
	Route::get('logout', function (){
		Auth::logout();
		return redirect('/');
	});







	




	


	

app/Http/Controllers/UsuarioController.php
<?php

namespace App\Http\Controllers;
use Illuminate\Http\Request;

use App\User;
use App\Vendedor;
use App\TipoUsuario;
use App\Menu;
use App\Permisos;
use Auth;


class UsuarioController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

       $datos['usuarios_table'] = User::where([['activo','1'],['id_personal','!=','0']])->orderBy('id','DESC')->get();

        return view('usuarios.index')->with($datos);
    }



    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        
        $datos['tipo_usuario'] = TipoUsuario::where('activo','1')->get();
        $datos['menu'] = Menu::where('activo','1')->get();
        
        return view('usuarios.create')->with($datos);        
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
            try {

                if ($request->hasFile('avatar')) {
                    $file = $request->file('avatar');
                   
                    $name = time().$file->getClientOriginalName();

                    $file->move(public_path().'/images/',$name);


                    $tienda = new User();
                    $tienda->name = $request->name;
                    $tienda->email = $request->email;
                    $tienda->password = bcrypt($request->password);
                    $tienda->tipo_user = $request->tipo_user;
                    $tienda->imagen_usuario = $name;
                    $tienda->save();
                  
                }else{
                    
                    $tienda = new User();
                    $tienda->name = $request->name;
                    $tienda->email = $request->email;
                    $tienda->password = bcrypt($request->password);
                    $tienda->tipo_user = $request->tipo_user;
                    $tienda->save();
                
                
                } 

                


                return redirect()->route('usuarios.index');
                //return response()->json(['success'=>'Se ha Agegado con Exito']);
            } catch (\Exception $e) {
              dd($e->getMessage());
            }
        
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
     public function show($id)
    {
        
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $datos['tipo_usuario'] = TipoUsuario::where('activo','1')->get();
        $datos['usuarios'] = User::find($id);
        $datos['menu'] = Menu::where('activo','1')->get();
        $datos['cuantas'] = Menu::where([['activo','1']])->count();

        $usuario = Auth::user()->id_peronal;


        $datos['permisos'] = Permisos::
        join('menu', 'permisos.id_permisos', '=', 'menu.id')->
        select(
                'permisos.id',
             'permisos.id_permisos',
              'menu.nombre'
          )->where([
          ['permisos.activo', '=', '1'],
          ['permisos.id_usuario', '=', $datos['usuarios']->id_personal],

        ])->get();

         
        return view('usuarios.create')->with($datos);    
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request,$id)
    {
            

        try {
            
            if ($request->hasFile('avatar')) {
                    $file = $request->file('avatar');
                   
                    $name = time().$file->getClientOriginalName();

                    $file->move(public_path().'/images/',$name);

                   

                    $tienda = User::find($id);
                    $tienda->name = $request->name;
                    $tienda->email = $request->email;
                    $tienda->id_personal = $request->id_personal;
                    $tienda->password = bcrypt($request->password);
                    $tienda->password_name = $request->password;
                    $tienda->tipo_user = $request->tipo_user;
                    $tienda->imagen_usuario = $name;
                    $tienda->save();
                  
                }else{

                    

                    $tienda = User::find($id);
                    $tienda->name = $request->name;
                    $tienda->email = $request->email;
                    $tienda->id_personal = $request->id_personal;
                    $tienda->password = bcrypt($request->password);
                    $tienda->password_name = $request->password;
                    $tienda->tipo_user = $request->tipo_user;
                    $tienda->save();
                
                
                }            
            


            Vendedor::where([['activo','1'],['id',$tienda->id_personal]])->update([
              "password" => $request->password
            ]);
            return redirect()->route('usuarios.index');
           //return response()->json(['success'=>'Se ha Editado con Exito']);

        } catch (\Exception $e) {
          dd($e->getMessage());
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $tienda = User::find($id);
        $tienda->activo = 0;
        $tienda->save();


        Vendedor::where([['activo','1'],['id',$id]])->update([
          "activo" => 0
        ]);

        return redirect()->route('usuarios.index');
    }


    public function permisos(Request $request)
    {


        
        try {

        foreach ($request->permisos as $value) {
            $permisos = new Permisos();
            $permisos->id_usuario = $request->id_personal;
            $permisos->id_permisos = $value['permiso_id'];
            $permisos->tipo_user = $request->tipo_user;
            $permisos->id = $request->id;
            $permisos->save();
        }
        

        return response()->json(['success'=>'Se han Agegado los Permisos']);

        } catch (\Exception $e) {
          dd($e->getMessage());
        }
    }


    public function borrar_permisos(Request $request){
       
        try {
            $permisos = Permisos::find($request->id);
            $permisos->activo = 0;
            $permisos->save();


        } catch (Exception $e) {
            dd($e->getMessage());
        }
    }






}

resources/views/usuarios/create.blade.php
@extends('layouts.inicio')

@section('content')
<style type="text/css" media="screen">
.select2-container--default .select2-selection--multiple .select2-selection__choice {
background-color: 
#3c8dbc;
border-color:
#367fa9;
padding: 1px 10px;
color:
    #fff;
}
.my-custom-scrollbar {
position: relative;
height: 200px;
overflow: auto;
}
.table-wrapper-scroll-y {
display: block;
}
</style>
<div class="col-md-12">
	<div class="box box-primary">
	    <div class="box-header with-border">
	    	@isset($usuarios)
	    	<h3 class="box-title">Actualizar Usuario</h3>
			@else
			<h3 class="box-title">Nuevo Usuario</h3>
			@endisset
	    </div>
	    <!-- /.box-header -->
	    <!-- form start -->

	    @isset($usuarios)
	        <form action="{{ route('usuarios.update',$usuarios->id) }}" method="POST" enctype="multipart/form-data">
	        @csrf
	        @method('PUT')
	      @else
	        <form action="{{ route('usuarios.store') }}" method="POST" enctype="multipart/form-data">
	        @csrf
	      @endisset
	      <div class="box-body">
	      	<div class="col-md-6">
	      	<div class="form-group">
	          <label for="exampleInputPassword1">Nombre del Usuario</label>
	          <input type="text" class="form-control" name="name" placeholder="Nombre de Articulo" value="@isset($usuarios){{ $usuarios->name }}@endisset">
	        </div>
	    	</div>
	    	<div class="col-md-6">
		        <div class="form-group">
		          <label for="exampleInputEmail1">Correo Electronico</label>
		          <input type="text" class="form-control" name="email" placeholder="Correo Electronico" value="@isset($usuarios){{ $usuarios->email }}@endisset">
		        </div>
	    	</div>
	    	<div class="col-md-6">
		        <div class="form-group">
		          <label for="exampleInputPassword1">Password</label>
		          <input type="text" class="form-control" name="password" placeholder="Password" value="@isset($usuarios){{ $usuarios->password_name }}@endisset">
		        </div>
		    </div>

		    

	        <div class="col-md-6">
              	<div class="form-group">
	                <label>Tipo de Usuario</label>
	                <select class="form-control select2 select2-hidden-accessible" style="width: 100%;"  name="tipo_user" tabindex="-1" aria-hidden="true">
	                 @isset($usuarios)
	                	 <option value="{{ $usuarios->tipo_user }}">{{ $usuarios->_TipoUsuario->nombre }}</option>
	                 @else
	                 <option>Selecciona una Categoria</option>
	                 @endisset
	                  @foreach($tipo_usuario as $usuarios_tipo)
	                  <option value="{{ $usuarios_tipo->id }}">{{ $usuarios_tipo->nombre }}</option>
	                  @endforeach
	                </select>
            	</div>
              
            </div>
            
            <div class="col-md-12">

            	<div class="col-md-6 ">
	              	<div class="form-group">
		                <label>Permisos</label>
		                <select class="form-control select2 select2-hidden-accessible" style="width: 100%;" id="id_permiso" name="id_permiso" tabindex="-1" aria-hidden="true">
		                 <option value="0">Selecciona un Permiso</option>
		                  @foreach($menu as $permiso)
		                  <option value="{{ $permiso->id }}">{{ $permiso->nombre }}</option>
		                  @endforeach
		                </select>
	            	</div>
	              	<br>
	              	<button type="button" class="btn btn-primary pull-right" id="agregarArticulo"><i class="fa fa-check"></i> Agregar</button>


	              	<div class="row">
				        <div class="col-xs-12 table-responsive">
				        	<label>Tabla Permisos de Usuario</label>
				        <div class="table-wrapper-scroll-y my-custom-scrollbar">

		  				<table class="table table-bordered table-striped mb-0" id="tablaArticulo" style=" text-align: center; ">

				            <thead>
				            <tr >
				              <th>Permiso</th>
				              <th>Accion</th>
				            </tr>
				            </thead>
				            <tbody>
				            	@isset($permisos)
				            		@foreach($permisos as $key => $permiso)
				            		<input type="hidden" id="objeto" value="{{ json_encode($key) }}">
				            			<tr id="filas{{ $permiso->id }}">
				            				<td>{{ $permiso->nombre }}</td>
				            				<td><button type="button" class="btn btn-danger" onclick="eliminarMayor({{ $permiso->id }})" ><i class="fa fa-trash"></i></button></td>
				            			</tr>
				            		@endforeach
				            	@endisset
				            </tbody>
				          </table>
				          </div>
				        </div>
				        <!-- /.col -->
				      </div>
				      
			        	<button type="button" class="btn btn-primary btn-submit pull-right"><i class="fa fa-check"></i> Agregar Permisos</button>

            	</div>


            	<div class="col-md-6">

	        		 @isset($usuarios)
		            <div class="col-md-6">
		              	<div class="form-group">
			                <label>Imagen de Usuario</label>
			                <div style="height: 20px;"></div>
			                <img src="../../images/{{ $usuarios->imagen_usuario }}" alt="" width="120" height="120">
			                <br>
			                <label>Cambiar Imagen</label>
		                    <input type="file"  name="avatar" value="">
			            </div>
			        </div>


		            
		            @else
		            <div class="col-md-6">
				        <div class="form-group">
				          <label for="exampleInputPassword1">Imagen del Usuario</label>
				          <input type="file"  name="avatar" value="">
				        </div>
				    </div>
				    @endisset
            	</div>

            </div>

		      

		      <!-- /.row -->
		    


           
            
            
            
		    
            @isset($usuarios)
            <input type="hidden" name="id_personal" value="@isset($usuarios){{ $usuarios->id_personal }}@endisset">
            <input type="hidden" name="tipo_user_2" value="@isset($usuarios){{ $usuarios->tipo_user }}@endisset">
            <input type="hidden" name="id" value="@isset($usuarios){{ $usuarios->id }}@endisset">
	        @endisset
	      </div>
	      <!-- /.box-body -->

	      <div class="box-footer">
	      	<a href="{{ url('usuarios') }}" ><button type="button" class="btn btn-warning"><i class="fa fa-arrow-left"></i> Regresar</button></a>
	      	@isset($usuarios)
	      	<button type="submit" class="btn btn-primary "><i class="fa fa-repeat"></i> Actualizar</button>
	      	@else
	        <button type="submit" class="btn btn-primary "><i class="fa fa-save"></i> Agregar</button>
	        @endisset
	      </div>
	    </form>
	  </div>
</div>



<script>
	var arrayAsp = [];
    
  		var objAsp = {};
	$(document).ready( function () {

		


	$(document).on("click","#agregarArticulo",function(e){
      	e.preventDefault();

     
      	
      	var permiso_id = $('#id_permiso').val();
      	console.log(permiso_id);
      	var permiso = $('select[name="id_permiso"] option:selected').text();


      	if (permiso_id == 0 ) {
                swal({title: "Cuidado!", text: "campos vacios", type: "warning"}, function(){ } );
	     
	     }else{

	     	objAsp = {
                      
                      permiso_id : $('#id_permiso').val(),
                      permiso: $('select[name="id_permiso"] option:selected').text(),
                    }


                    agregarAsp(objAsp);
                    arrayAsp.push(objAsp);

	      }



  		});

		




		$(".btn-submit").click(function(e){
        e.preventDefault();
        ////////// limpieza

        var id_personal = $('input[name=id_personal]').val();
        var tipo_user = $('input[name=tipo_user_2]').val();


        if(arrayAsp == 0){
        	swal({title: "Cuidado!", text: "No Existen Permisos Nuevos", type: "warning"}, function(){ } );
        }else{
        	$.ajax({

	           type:"POST",

	           url:"/permisos",
	           headers: {
				      'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
				     },
	           data:{
	           	tipo_user:tipo_user,
	           	id_personal:id_personal,
				permisos:arrayAsp,
	           },
	           
	            success:function(data){
	                swal({title: "Felicidades!", text: data.success, type: "success"}, function(){  } );
	            }


	        });
        }


        	

       
        });
	    
}); 


	var contador_asp = 0;
	function agregarAsp(objAsp){
	  //construccion de tabla
	    var tr = '<tr class="borrar_aspc_create" id="filas'+contador_asp+'">'+
	    
	    '<td>'+objAsp.permiso+'<input type="hidden" name="id_materia[]" value="'+objAsp.permiso_id+'" id="nvel_educativo_nombre'+contador_asp+'"/></td>'+
	    '<td style=" text-align: center; "><div  class="btn btn-danger" onclick="eliminarAsp_create('+contador_asp+')"> <i class="fa fa-trash"></i></div></td>'
	    '</tr>';




      
	    $("#tablaArticulo").append(tr);
	    //limpiar campos

	    $('#id_permiso').val('');
	    
	 contador_asp ++;
   //////////////////////////////////////
                    
	}

//$(document).on("click",".borrar_figura",function(e){
//      var id_figura_nueva = $(this).attr('figura_nueva_id');
//      e.preventDefault();
//      var id = $('#figura_nueva').val();
//      arrayFiguras.splice(id, 1);
//      $('#id-figura-'+id_figura_nueva).remove();
//  });

	function eliminarAsp_create(id) {
	    console.log(id);
	    
	    arrayAsp.splice(id,1);

	      $('#filas'+id).remove();
	    }


///////////////////////////////
        function eliminarMayor(id) {

        	console.log()
            var objeto = $('#objeto').val();

            eval(objeto);
            arrayAsp = JSON.parse(objeto);
            

            $.ajax({
              url: "/borrar_permisos",
              type: "POST",
              headers:  {'X-CSRF-TOKEN':$("meta[name='csrf-token']").attr('content')},
              data: {id: id}
            });

            $('#filas'+id).remove();

        }


</script>
@endsection

resources/views/usuarios/index.blade.php
@extends('layouts.inicio')

@section('content')
<div class="col-md-12">
  <!-- MAP & BOX PANE -->
  <div class="box box-primary">
    <div class="box-header with-border">
      
      <h3 class="box-title"><img class="img-circle" src="../images/<?php list($confi) = configuracion(); print_r($confi->logo_empresa);?>" alt="User Avatar" heigth="30" width="30"> Usuarios <?php list($confi) = configuracion(); print_r($confi->nombre_empresa);?> </h3>


      <div class="box-tools pull-right">
        <!--<a href="{{ route('usuarios.create') }}" class="btn btn-primary"> Nuevo Usuario</a>-->
      </div>
    </div>
    <!-- /.box-header -->
    <div class="box-body no-padding">

    	  <table id="example" class="display" style="width:100%">
	        <thead>
	          <tr align="center">
              <th>Nombre de Usuario</th>
	            <th>Correo Electronico</th>
	            <th>Password</th>
	            <th>Tipo de Usuario</th>
	            <th>Acciones</th>
	          </tr>
	        </thead>
	        <tbody>
	          @foreach ($usuarios_table as $usuario)
                  <tr align="center">
                      <td>{{ $usuario->name }}</td>
                      <td>{{ $usuario->email }}</td>
                      <td>{{ $usuario->password_name }}</td>
                      <td>{{ $usuario->_TipoUsuario->nombre }}</td>
                      <td >
                        <form action="{{ route('usuarios.destroy',$usuario->id )}}" method="POST">
                                      @csrf
                                      @method('DELETE')
                        <div class="btn-group">
                          <button type="button" class="btn btn-warning"><a href="{{ route('usuarios.edit',$usuario->id)}}" style="color:#fff;"><i class="fa fa-pencil"></i> Editar</a></button>
                            <button class="btn btn-danger" type="submit"><i class="fa fa-trash"></i> Eliminar</button>
                        </div>
                        </form>
                      </td>
                  </tr>
                @endforeach
	        </tbody>
	      </table>
    </div>
    <!-- /.box-body -->
  </div>
  <!-- /.box -->

</div>
<script>
  $(document).ready(function() {
      
      $('#example').DataTable({
    
    "scrollY": 300,
    "scrollX": true,
    "pagingType": "full_numbers",
   language: {
    processing:     "Tratamiento en curso...",
    search:         "Buscar&nbsp;:",
    lengthMenu:    "Mostrando _MENU_ registros por página",
    info:           "Mostrando página _START_ a _TOTAL_ Elementos",
    infoEmpty:      "No hay registros disponibles",
    infoFiltered:   "(Filtrado de _MAX_ registros totales)",
    infoPostFix:    "",
    loadingRecords: "Cargando...",
    zeroRecords:    "Ningun Resgistro",
    emptyTable:     "No hay datos disponibles por el momento.",
    paginate: {
        first:      "Primeramente",
        previous:   "Anteriormente",
        next:       "Siguiente",
        last:       "Ultimo"
    },
    aria: {
        sortAscending:  ": Activar para ordenar la columna en orden ascendente.",
        sortDescending: ": Activar para ordenar la columna en orden descendente."
    }
},

});
      
  } );
</script>
@endsection

resources/views/usuarios/lockscreen.blade.php
@extends('layouts.login')

@section('content')
<div class="lockscreen-wrapper">
  <div class="lockscreen-logo">
    <a href="../../index2.html"><b>Admin</b>LTE</a>
  </div>
  <!-- User name -->
  <div class="lockscreen-name">John Doe</div>

  <!-- START LOCK SCREEN ITEM -->
  <div class="lockscreen-item">
    <!-- lockscreen image -->
    <div class="lockscreen-image">
      <img src="../../dist/img/user1-128x128.jpg" alt="User Image">
    </div>
    <!-- /.lockscreen-image -->

    <!-- lockscreen credentials (contains the form) -->
    <form class="lockscreen-credentials">
      <div class="input-group">
        <input type="password" class="form-control" placeholder="password">

        <div class="input-group-btn">
          <button type="button" class="btn"><i class="fa fa-arrow-right text-muted"></i></button>
        </div>
      </div>
    </form>
    <!-- /.lockscreen credentials -->

  </div>
  <!-- /.lockscreen-item -->
  <div class="help-block text-center">
    Enter your password to retrieve your session
  </div>
  <div class="text-center">
    <a href="login.html">Or sign in as a different user</a>
  </div>
  <div class="lockscreen-footer text-center">
    Copyright &copy; 2014-2016 <b><a href="https://adminlte.io" class="text-black">Almsaeed Studio</a></b><br>
    All rights reserved
  </div>
</div>


@endsection